### ISSUE TITLE
Sauce

### ISSUE THREAD

**Issue by AyHa1810** [LegacyGamerHD/EmiliaMC#6]
@LegacyGamerHD  Gimus da sauce of every anime pfp or any picture u use!

Sry I m being stupid lol

**Comment by WesleyVanNeck** [comment]
curently  using https://www.google.com/search?q=cooking+of+valkyries+background&rlz=1C1CHBD_enNL925NL925&sxsrf=ALeKk01HY3Jtbx4gzF4z3kdOowjjIPb8KA:1604345055146&tbm=isch&source=iu&ictx=1&fir=_vlAnHIx-Q40WM%252CcMO_v-2INcEWNM%252C_&vet=1&usg=AI4_-kQvtmq6OOwjQKjEl40XMtMv_0TFqw&sa=X&ved=2ahUKEwj5ne-Iy-TsAhWGLewKHUwbARsQ9QF6BAgKECM#imgrc=GgAUFaWeAmWo7M

**Comment by AyHa1810** [comment]
you actually responded lmao XD

**Comment by AyHa1810** [comment]
Aay wat? Honkai Impact 3rd is the game made by same developers (miHoYo) as Genshin Impact!? Wow

**Comment by WesleyVanNeck** [comment]
yep

**Comment by AyHa1810** [comment]
What if I ask again?

**Comment by WesleyVanNeck** [comment]
fine i geussh

**Comment by AyHa1810** [comment]
Sus pls

**Comment by AyHa1810** [comment]
For research purposes

**Comment by WesleyVanNeck** [comment]
Old img https://www.zerochan.net/2746335

**Comment by WesleyVanNeck** [comment]
New one https://www.zerochan.net/2427516

**Comment by AyHa1810** [comment]
Umm, thanks I think!?

**Comment by AyHa1810** [comment]
Ok now I am closing this, cuz why not!
